export const TodoTaskActions = [
  {
    name: 'todo_task_complete',
    label: 'Mark Complete',
    icon: 'check-circle-2',
    type: 'api' as const,
    locations: ['record_header' as const, 'list_item' as const, 'list_toolbar' as const],
    visible: 'is_completed === false',
    bulkEnabled: true,
    confirmText: 'Mark this task as complete?',
    refreshAfter: true,
    successMessage: 'Task marked as complete',
  },
  {
    name: 'todo_task_start',
    label: 'Start Task',
    icon: 'play',
    type: 'api' as const,
    locations: ['record_header' as const, 'list_item' as const],
    visible: "status === 'Backlog' || status === 'Todo'",
    refreshAfter: true,
    successMessage: 'Task moved to In Progress',
  },
  {
    name: 'todo_task_clone',
    label: 'Clone Task',
    icon: 'copy',
    type: 'api' as const,
    locations: ['record_more' as const],
    refreshAfter: true,
    successMessage: 'Task cloned successfully',
  },
  {
    name: 'todo_task_defer',
    label: 'Defer Task',
    icon: 'clock',
    type: 'api' as const,
    locations: ['record_header' as const],
    visible: "status !== 'Done'",
    params: [
      { name: 'defer_until', label: 'Defer Until', type: 'date' as const, required: true },
    ],
    refreshAfter: true,
    successMessage: 'Task deferred',
  },
  {
    name: 'todo_task_set_reminder',
    label: 'Set Reminder',
    icon: 'bell',
    type: 'api' as const,
    locations: ['record_more' as const],
    params: [
      { name: 'reminder_date', label: 'Reminder Date', type: 'datetime' as const, required: true },
      { name: 'reminder_note', label: 'Note', type: 'text' as const },
    ],
    successMessage: 'Reminder set',
  },
  {
    name: 'todo_task_assign',
    label: 'Assign',
    icon: 'user-plus',
    type: 'api' as const,
    locations: ['record_header' as const, 'list_item' as const, 'list_toolbar' as const],
    bulkEnabled: true,
    params: [
      { name: 'assignee', label: 'Assignee', type: 'text' as const, required: true },
    ],
    refreshAfter: true,
    successMessage: 'Task assigned',
  },
];
