/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Auto-Layout for ObjectForm
 *
 * Provides intelligent, zero-configuration default layout for metadata-driven forms.
 * When the user has not explicitly set columns/colSpan/sections, this module
 * infers optimal layout based on field count and field types.
 *
 * Priority: User configuration > Auto-layout inference
 */

import type { FormField } from '@object-ui/types';

/** Field types that should span full width in multi-column layouts */
const WIDE_FIELD_TYPES = new Set([
  'field:textarea',
  'field:markdown',
  'field:html',
  'field:grid',
  'field:rich-text',
  'textarea',
  'markdown',
  'html',
  'grid',
  'rich-text',
]);

/** Object field types that are auto-generated and should be hidden in create mode */
const AUTO_GENERATED_FIELD_TYPES = new Set([
  'formula',
  'summary',
  'auto_number',
  'autonumber',
]);

/**
 * Check if a field type is "wide" (should span full row in multi-column layout).
 */
export function isWideFieldType(type: string): boolean {
  return WIDE_FIELD_TYPES.has(type);
}

/**
 * Check if an object field type is auto-generated (formula, summary, auto_number).
 */
export function isAutoGeneratedFieldType(type: string): boolean {
  return AUTO_GENERATED_FIELD_TYPES.has(type);
}

/**
 * Infer optimal number of columns based on the number of visible fields
 * and whether any wide fields are present.
 *
 * Rules:
 * - 0-3 fields → 1 column
 * - 4+ fields → 2 columns
 */
export function inferColumns(fieldCount: number): number {
  if (fieldCount <= 3) return 1;
  return 2;
}

/**
 * Apply colSpan to wide fields so they span the full row.
 * Only sets colSpan if the field does not already have one explicitly set.
 *
 * @returns A new array of fields with colSpan applied where needed.
 */
export function applyAutoColSpan(fields: FormField[], columns: number): FormField[] {
  if (columns <= 1) return fields;

  return fields.map(field => {
    // User-defined colSpan takes priority
    if (field.colSpan !== undefined) return field;

    // Wide field types should span full row
    if (isWideFieldType(field.type)) {
      return { ...field, colSpan: columns };
    }

    return field;
  });
}

/**
 * Filter out auto-generated/readonly fields for create mode.
 * These fields (formula, summary, auto_number) are computed server-side
 * and should not appear in create forms.
 *
 * @param fields - The form fields array
 * @param objectSchema - The object schema with original field metadata
 * @returns Filtered fields array
 */
export function filterCreateModeFields(
  fields: FormField[],
  objectSchema: any
): FormField[] {
  if (!objectSchema?.fields) return fields;

  return fields.filter(field => {
    const objField = objectSchema.fields[field.name];
    if (!objField) return true; // keep fields not in schema (custom fields)

    return !isAutoGeneratedFieldType(objField.type);
  });
}

/**
 * Infer an appropriate modal size based on the number of layout columns.
 * Used to auto-upgrade the modal width when auto-layout detects multi-column forms.
 *
 * Mapping:
 * - 1 column  → 'default' (max-w-lg)
 * - 2 columns → 'lg'      (max-w-2xl)
 * - 3 columns → 'xl'      (max-w-4xl)
 * - 4+ columns → 'full'   (max-w-[95vw])
 */
export function inferModalSize(columns: number): 'sm' | 'default' | 'lg' | 'xl' | 'full' {
  if (columns <= 1) return 'default';
  if (columns === 2) return 'lg';
  if (columns === 3) return 'xl';
  return 'full';
}

/**
 * Main auto-layout orchestrator.
 * Applies intelligent defaults only when the user has not explicitly configured layout.
 *
 * @param formFields - Generated form fields
 * @param objectSchema - The original object schema (with field types)
 * @param schemaColumns - User-provided columns (from ObjectFormSchema)
 * @param mode - Form mode ('create' | 'edit' | 'view')
 * @returns Object with processed fields and inferred columns
 */
export function applyAutoLayout(
  formFields: FormField[],
  objectSchema: any,
  schemaColumns: number | undefined,
  mode: string | undefined
): { fields: FormField[]; columns: number | undefined } {
  let fields = [...formFields];

  // Step 1: Filter auto-generated fields in create mode
  if (mode === 'create') {
    fields = filterCreateModeFields(fields, objectSchema);
  }

  // Step 2: If user explicitly set columns, respect it but still apply auto colSpan
  if (schemaColumns !== undefined) {
    fields = applyAutoColSpan(fields, schemaColumns);
    return { fields, columns: schemaColumns };
  }

  // Step 3: Infer columns from field count
  const columns = inferColumns(fields.length);

  // Step 4: Apply auto colSpan for wide fields
  fields = applyAutoColSpan(fields, columns);

  return { fields, columns };
}
