/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { ComponentRegistry } from '@object-ui/core';
import { ObjectForm } from './ObjectForm';

export { ObjectForm };
export type { ObjectFormProps } from './ObjectForm';
export { FormSection } from './FormSection';
export type { FormSectionProps } from './FormSection';
export {
  applyAutoLayout,
  inferColumns,
  inferModalSize,
  isWideFieldType,
  isAutoGeneratedFieldType,
  applyAutoColSpan,
  filterCreateModeFields,
} from './autoLayout';
export { TabbedForm } from './TabbedForm';
export type { TabbedFormProps, TabbedFormSchema, FormSectionConfig } from './TabbedForm';
export { WizardForm } from './WizardForm';
export type { WizardFormProps, WizardFormSchema } from './WizardForm';
export { SplitForm } from './SplitForm';
export type { SplitFormProps, SplitFormSchema } from './SplitForm';
export { DrawerForm } from './DrawerForm';
export type { DrawerFormProps, DrawerFormSchema } from './DrawerForm';
export { ModalForm } from './ModalForm';
export type { ModalFormProps, ModalFormSchema } from './ModalForm';
export { EmbeddableForm } from './EmbeddableForm';
export type { EmbeddableFormProps, EmbeddableFormConfig } from './EmbeddableForm';
export { FormAnalytics } from './FormAnalytics';
export type { FormAnalyticsProps, FormSubmissionMetric } from './FormAnalytics';

// Register object-form component
const ObjectFormRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  return <ObjectForm schema={schema} />;
};

ComponentRegistry.register('object-form', ObjectFormRenderer, {
  namespace: 'plugin-form',
  label: 'Object Form',
  category: 'plugin',
  inputs: [
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'mode', type: 'enum', label: 'Mode', enum: ['create', 'edit', 'view'] },
    { name: 'formType', type: 'enum', label: 'Form Type', enum: ['simple', 'tabbed', 'wizard', 'split', 'drawer', 'modal'] },
    { name: 'sections', type: 'array', label: 'Sections' },
    { name: 'title', type: 'string', label: 'Title' },
    { name: 'description', type: 'string', label: 'Description' },
    { name: 'layout', type: 'enum', label: 'Layout', enum: ['vertical', 'horizontal', 'inline', 'grid'] },
    { name: 'columns', type: 'number', label: 'Columns' },
    // Tabbed
    { name: 'defaultTab', type: 'string', label: 'Default Tab' },
    { name: 'tabPosition', type: 'enum', label: 'Tab Position', enum: ['top', 'bottom', 'left', 'right'] },
    // Wizard
    { name: 'allowSkip', type: 'boolean', label: 'Allow Skip Steps' },
    { name: 'showStepIndicator', type: 'boolean', label: 'Show Step Indicator' },
    // Split
    { name: 'splitDirection', type: 'enum', label: 'Split Direction', enum: ['horizontal', 'vertical'] },
    { name: 'splitSize', type: 'number', label: 'Split Panel Size (%)' },
    { name: 'splitResizable', type: 'boolean', label: 'Split Resizable' },
    // Drawer
    { name: 'drawerSide', type: 'enum', label: 'Drawer Side', enum: ['top', 'bottom', 'left', 'right'] },
    { name: 'drawerWidth', type: 'string', label: 'Drawer Width' },
    // Modal
    { name: 'modalSize', type: 'enum', label: 'Modal Size', enum: ['sm', 'default', 'lg', 'xl', 'full'] },
  ]
});

// Register as view:form for the standard view protocol
// This allows using { type: 'view:form', objectName: '...' } in schemas
// skipFallback prevents overwriting the basic 'form' component from @object-ui/components
ComponentRegistry.register('form', ObjectFormRenderer, {
  namespace: 'view',
  skipFallback: true,
  label: 'Data Form View',
  category: 'view',
  inputs: [
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'mode', type: 'enum', label: 'Mode', enum: ['create', 'edit', 'view'] },
  ]
});

// Note: 'form' type (without namespace) is handled by @object-ui/components Form component
// This plugin registers as 'view:form' (with view namespace) for the view protocol
// ObjectForm internally uses { type: 'form' } to render the basic Form component

// Register embeddable-form component for standalone public forms
import { EmbeddableForm } from './EmbeddableForm';

const EmbeddableFormRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  return <EmbeddableForm config={schema} />;
};

ComponentRegistry.register('embeddable-form', EmbeddableFormRenderer, {
  namespace: 'plugin-form',
  label: 'Embeddable Form',
  category: 'plugin',
  inputs: [
    { name: 'formId', type: 'string', label: 'Form ID', required: true },
    { name: 'objectName', type: 'string', label: 'Object Name', required: true },
    { name: 'title', type: 'string', label: 'Form Title' },
    { name: 'description', type: 'string', label: 'Description' },
    { name: 'fields', type: 'array', label: 'Fields' },
    { name: 'allowMultiple', type: 'boolean', label: 'Allow Multiple Submissions' },
  ]
});

// Register form-analytics component for submission dashboards
import { FormAnalytics } from './FormAnalytics';

const FormAnalyticsRenderer: React.FC<{ schema: any }> = ({ schema }) => {
  return <FormAnalytics formId={schema.formId} formTitle={schema.formTitle} metrics={schema.metrics || { totalSubmissions: 0 }} />;
};

ComponentRegistry.register('form-analytics', FormAnalyticsRenderer, {
  namespace: 'plugin-form',
  label: 'Form Analytics',
  category: 'plugin',
  inputs: [
    { name: 'formId', type: 'string', label: 'Form ID', required: true },
    { name: 'formTitle', type: 'string', label: 'Form Title' },
    { name: 'metrics', type: 'object', label: 'Submission Metrics' },
  ]
});
